import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

import "bootstrap/dist/css/bootstrap.css";
import "../../public/assets/css/variables.css";
import "../../public/assets/css/variables-orange.css";
import "../../public/assets/css/main.css";

import "../../public/assets/vendor/bootstrap/css/bootstrap.min.css";
import "../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css";
import "../../public/assets/vendor/aos/aos.css";
import "../../public/assets/vendor/glightbox/css/glightbox.min.css";
import "../../public/assets/vendor/swiper/swiper-bundle.min.css";

import Header from "./navbar/page";

import Footer from "./footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head></head> */}
      <body className={inter.className}>
        {children}
        {/* <script src="js/bootstrap.bundle.min.js" /> */}
        {/* <script src="/vendor/bootstrap/js/bootstrap.bundle.min.js" /> */}
        <Header />
        <Script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js" />
        <Script src="assets/vendor/aos/aos.js" />
        <Script src="assets/vendor/glightbox/js/glightbox.min.js" />
        <Script src="assets/vendor/isotope-layout/isotope.pkgd.min.js" />
        <Script src="assets/vendor/swiper/swiper-bundle.min.js" />
        {/* <Script src="assets/vendor/php-email-form/validate.js" /> */}
        <Script src="assets/js/main.js" />

        <Footer />
      </body>
    </html>
  );
}
